version: '3'
services:

  #Added Debug configurations - Exposing port and added required JAVA_OPTIONS for debug
  # for both backend and frontend

  workflow-backend:
    ports:
    - "${WORKFLOW_BACKEND_DEBUG_PORT}:${WORKFLOW_BACKEND_DEBUG_PORT}"
    environment:
    - JAVA_OPTIONS=${JAVA_OPTIONS} -Xdebug -agentlib:jdwp=transport=dt_socket,address=${WORKFLOW_BACKEND_DEBUG_PORT},server=y,suspend=n

  workflow-frontend:
    ports:
    - "${WORKFLOW_FRONTEND_DEBUG_PORT}:${WORKFLOW_FRONTEND_DEBUG_PORT}"
    environment:
    - JAVA_OPTIONS=${JAVA_OPTIONS} -Xdebug -agentlib:jdwp=transport=dt_socket,address=${WORKFLOW_FRONTEND_DEBUG_PORT},server=y,suspend=n