version: '3'
services:
  
  workflow-cassandra-init:
    image: "${REGISTRY}onap/workflow-init:${IMAGE_TAG}"  
    environment:
        - CS_HOST
        - CS_AUTHENTICATE
        - CS_USER
        - CS_PASSWORD
        - CS_PORT=${WORKFLOW_CASSANDRA_INIT_PORT}

  workflow-backend:
    depends_on:
      - workflow-cassandra-init
    image: "${REGISTRY}onap/workflow-backend:${IMAGE_TAG}"
    environment:
        - JAVA_OPTIONS
        - CS_HOSTS=${CS_HOST}
        - CS_USER
        - CS_PASSWORD
        - CS_PORT=${WORKFLOW_BACKEND_CASSANDRA_PORT}
        - SDC_PROTOCOL
        - SDC_ENDPOINT="${SDC_HOST}:8080"
        - SDC_USER
        - SDC_PASSWORD

  workflow-frontend:
    depends_on:
      - workflow-cassandra-init
      - workflow-backend
    image: "${REGISTRY}onap/workflow-frontend:${IMAGE_TAG}"
    ports:
        - "${WORKFLOW_FRONTEND_PORT}:8080"
    environment:
        - JAVA_OPTIONS
        - BACKEND=http://workflow-backend:8080
