version: '3'
services:
  
  workflow-cassandra-init:
    image: "${REGISTRY}onap/workflow-init:${IMAGE_TAG}"  
    environment:
        - CS_HOST
        - CS_AUTHENTICATE
        - CS_USER
        - CS_PASSWORD
        - CS_PORT=${CASSANDRA_INIT_PORT}

  workflow-backend:
    depends_on:
      - workflow-cassandra-init
    image: "${REGISTRY}onap/workflow-backend:${IMAGE_TAG}"
    environment:
        - JAVA_OPTIONS
        - CS_HOSTS=${CS_HOST}
        - CS_USER
        - CS_PASSWORD
        - CS_PORT=${CASSANDRA_PORT}
        - SDC_PROTOCOL
        - SDC_ENDPOINT="${SDC_HOST}:8080"
        - SDC_USER
        - SDC_PASSWORD
        - SERVER_PORT
        - SERVER_SSL_ENABLED
        - SERVER_SSL_KEY_PASSWORD
        - SERVER_SSL_KEYSTORE_PATH
        - SERVER_SSL_KEYSTORE_TYPE
        - SERVER_SSL_TRUST_PASSWORD
        - SERVER_SSL_TRUSTSTORE_PATH
        - SERVER_SSL_TRUSTSTORE_TYPE
  workflow-frontend:
    depends_on:
      - workflow-cassandra-init
      - workflow-backend
    image: "${REGISTRY}onap/workflow-frontend:${IMAGE_TAG}"
    ports:
        - "${FRONTEND_PORT}:8080"
    environment:
        - JAVA_OPTIONS
        - BACKEND=http://workflow-backend:8080
        - KEYSTORE_PASSWORD
        - KEYSTORE_TYPE
        - KEYSTORE_PATH
        - KEYMANAGER_PASSWORD
        - TRUSTSTORE_PASSWORD
        - TRUSTSTORE_PATH
        - TRUSTSTORE_TYPE
        - IS_CLIENT_AUTH
        - IS_HTTPS