version: '3'
services:

  sdc-workflow-cassandra-init:
    image: "${REGISTRY}onap/sdc-workflow-init:${IMAGE_TAG}"
    environment:
        - CS_HOST
        - CS_AUTHENTICATE
        - CS_USER
        - CS_PASSWORD
        - CS_PORT
    networks:
      - sdc-network

  sdc-workflow-backend:
    depends_on:
      - sdc-workflow-cassandra-init
    image: "${REGISTRY}onap/sdc-workflow-backend:${IMAGE_TAG}"
    ports:
      - "8384:8080"
      - "10443:8443"
      - "8000:8000"
    environment:
        - JAVA_OPTIONS
        - CS_HOSTS=${CS_HOST}
        - CS_USER
        - CS_PASSWORD
        - CS_PORT
        - CS_AUTHENTICATE
        - CS_SSL_ENABLED
        - SDC_PROTOCOL
        - SDC_ENDPOINT=${SDC_HOST}:8080
        - SDC_USER
        - SDC_PASSWORD
        - SERVER_SSL_ENABLED
        - BASIC_AUTH_CREDENTIAL
    networks:
      - sdc-network

  sdc-workflow-frontend:
    depends_on:
      - sdc-workflow-cassandra-init
      - sdc-workflow-backend
    image: "${REGISTRY}onap/sdc-workflow-frontend:${IMAGE_TAG}"
    ports:
        - "8484:8080"
        - "11443:8443"
    environment:
        - JAVA_OPTIONS
        - BACKEND=http://sdc-workflow-backend:8080
        - BASIC_AUTH_CREDENTIAL
    networks:
      - sdc-network


networks:
  sdc-network:
    external: true
