version: '3'
services:

  sdc-workflow-cassandra-init:
    image: "${REGISTRY}onap/sdc-workflow-init:${IMAGE_TAG}"
    environment:
        - CS_HOST
        - CS_AUTHENTICATE
        - CS_USER
        - CS_PASSWORD
        - CS_PORT=${CASSANDRA_INIT_PORT}

  sdc-workflow-backend:
    depends_on:
      - sdc-workflow-cassandra-init
    image: "${REGISTRY}onap/sdc-workflow-backend:${IMAGE_TAG}"
    environment:
        - JAVA_OPTIONS
        - CS_HOSTS=${CS_HOST}
        - CS_USER
        - CS_PASSWORD
        - CS_PORT=${CASSANDRA_PORT}
        - SDC_PROTOCOL
        - SDC_ENDPOINT="${SDC_HOST}:8080"
        - SDC_USER
        - SDC_PASSWORD

  sdc-workflow-frontend:
    depends_on:
      - sdc-workflow-cassandra-init
      - sdc-workflow-backend
    image: "${REGISTRY}onap/sdc-workflow-frontend:${IMAGE_TAG}"
    ports:
        - "${FRONTEND_PORT}:8080"
    environment:
        - JAVA_OPTIONS
        - BACKEND=http://sdc-workflow-backend:8080
